on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"
    
name: build 

jobs:
  render:
    name: build
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://tbep-tech.r-universe.dev'
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            here
            tbeptools

      - name: Pull data
        run: Rscript -e 'source("R/build.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"